version: "3"

services:
  oracle:
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:latest

    # Provide passwords and other environment variables to container
    environment:
      - ORACLE_PASSWORD=oracle
#      - APP_USER=admin
#      - APP_USER_PASSWORD=admin

    # Forward Oracle port
    ports:
      - 1521:1521
